import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>     
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased max-w-[700px]`}>
        <h1 className="text-3xl font-bold m-4">Useless Tasker</h1>
        <nav className="">
          <Link className="bg-blue-500 text-white py-2 px-4 rounded-sm font-bold m-4" href="/polling">Polling</Link>
          <Link className="bg-red-500 text-white py-2 px-4 rounded-sm font-bold m-4" href="/signalr">SignalR</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
